
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    adapter:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    gauss_pool:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp32
        reduce_dtype: fp32
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    adapter:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    gauss_pool:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp32
        reduce_dtype: fp32
        buffer_dtype: fp32

dino:
  loss_weight: 1.0
  head_n_prototypes: 4096
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 1024
  koleo_loss_weight: 0.0
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: true
  head_n_prototypes: 4096
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 1024
train:
  batch_size_per_gpu: 100
  dataset_path: /SSD2T/synthetic0302/imagenet/view1
  output_dir: .
  saveckp_freq: 20
  seed: 0
  num_workers: 24
  OFFICIAL_EPOCH_LENGTH: 1356 # Manually set the epoch length, which is total samples / batch size / num_gpus
  cache_dataset: true
  centering: centering
  dataset: ImageNet
  log_period: 12

student:
  arch: ViT-L/14
  patch_size: 16
  layerscale: 0.0

  ffn_layer: mlp
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1

  adapter:
    embed_dim: 768
    qkv_dim: 576
    depth: 6
    num_heads: 9
    mlp_ratio: 2
    drop_path_rate: 0.1
    drop_path_uniform: true

teacher:
  momentum_teacher: 0.996
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30

optim:
  epochs: 100
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 1.0e-4
  warmup_epochs: 0
  min_lr: 5.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: lin_wrt_1024
  patch_embed_lr_mult: 1.0
  layerwise_decay: 1.0
  adamw_beta1: 0.9
  adamw_beta2: 0.999

crops:
  global_crops_scale:
  - 0.32
  - 1.0
  local_crops_number: 0
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224
  local_crops_size: 96

evaluation:
  eval_period_iterations: 1356*10  ### 10 epochs


